version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: mongo_englishabulary
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
